### ISSUE TITLE
Expresso Capstone (API) Summary

### ISSUE THREAD

**Issue by ad3429** [LCR-8/NodeJS-Capstone-Expresso#2]
**Rubric Score**
 
**Criteria 1: Table Creation (Migration File)**

- Score Level: 4/4
- Comment(s): migration.js includes code that creates all tables with the appropriate structure and relationships as defined in the spec. 

**Criteria 2: Implementation of API Specification and Functionality**

- Score Level: 4/4
- Comment(s): API implementation properly organized; route paths and functionality are implemented to spec; errors are handled; listening port can be configured via the PORT env variable.

**Criteria 3: Test Case Results (Are all Test Cases Passing?)**

- Score Level: 4/4
- Comment(s): Test cases pass

 
**Criteria 4: JavaScript and Express.js Fundamentals and Formatting**

- Score Level: 4/4
- Comment(s): Follows good JS practices throughout; proper use of functions, objects, Express.js routers, middleware

 
**Overall Score: 16/16**

Great job overall! It's clear that you understood the project requirements well and that you have a solid understanding of building Web API's. Keep up the good work!

**Comment by LCR-8** [comment]
Thanks!
Encouraging for my futur projects :)
